let mots = {
    Metiers: [
        "PILOTE", "BOULANGER", "DOCTEUR", "AVOCAT", "POMPIER", "ARTISTE", "CUISINIER", "POLICIER", "FACTEUR", "COIFFEUR",
        "MARECHAL", "DENTISTE", "JUGE", "PLOMBIER", "SOUDEUR", "LIBRAIRE", "MARIN", "ASTRONAUTE", "MAÇON", "NOTAIRE",
        "PEINTRE", "FORGERON", "BOUCHER", "MENUISIER", "INFIRMIER", "ARCHITECTE", "VETERINAIRE", "PHARMACIEN", "JARDINIER", "MECANICIEN",
        "CHIRURGIEN", "ELECTRICIEN", "TAILLEUR", "PAYSAN", "FLEURISTE", "CHAUFFEUR", "ECRIVAIN", "JOURNALISTE", "SERVEUR", "PATISSIER",
        "HORLOGER", "BIJOUTIER", "COUTURIER", "OPTICIEN", "BANQUIER", "DESSINATEUR", "CONCIERGE", "SOUDEUR", "COUVREUR", "ANIMATEUR"
    ],
    Objets: [
        "ORDINATEUR", "TELEPHONE", "VOITURE", "LAMPE", "TABLE", "MONTRE", "VALISE", "CRAYON", "MIROIR", "MARTEAU",
        "BUREAU", "CISEAUX", "CLAVIER", "GUITARE", "LUNETTES", "BOTTES", "CANAPE", "RADIO", "CAMERA", "REVEIL",
        "BROSSE", "ASSIETTE", "VOLANT", "PARAPLUIE", "TOURNEVIS", "BICYCLETTE", "TELEVISION", "LIVRE", "CHAIGNON", "BOUTEILLE",
        "COUTEAU", "FOURCHETTE", "CUILLERE", "POUBELLE", "RIDEAU", "FENETRE", "PORTE", "TAPIS", "CADRE", "TASSE",
        "LIT", "ARMOIRE", "COUSSIN", "PEIGNE", "CRAVATE", "BAGUE", "CASQUETTE", "SAC", "CLEF", "FAUTEUIL"
    ],
    Animaux: [
        "CHIEN", "CHAT", "LION", "TIGRE", "ZEBRE", "LOUP", "RENARD", "OURS", "LAPIN", "SINGE",
        "GIRAFE", "REQUIN", "SERPENT", "CHEVAL", "POULE", "SOURIS", "DAUPHIN", "TORTUE", "CANARD", "FOURMI",
        "HIBOU", "CORBEAU", "MAMMOUTH", "BALEINE", "ABEILLE", "ELEPHANT", "KANGOUROU", "PANDA", "CROCODILE", "AIGLE",
        "PIRANHA", "GORILLE", "RHINOCEROS", "HIPPOPOTAME", "CERF", "ECUREUIL", "VACHE", "MOUTON", "COCHON", "CHEVRE",
        "PIGEON", "PERROQUET", "GRENOUILLE", "HOMARD", "CRABE", "MEDUSE", "SCORPION", "ARAIGNEE", "PAPILLON", "LAMA"
    ],
    Fruits: [
        "POMME", "BANANE", "ORANGE", "MANGUE", "RAISIN", "POIRE", "ANANAS", "PECHE", "CERISE", "KIWI",
        "CITRON", "MELON", "FRAISE", "ABRICOT", "FIGUE", "PRUNE", "GRENADE", "LITCHI", "TOMATE", "DATTE",
        "COCO", "GOYAVE", "PAMPLEMOUSSE", "MURE", "CASSIS", "FRAMBOISE", "MYRTILLE", "PASTEQUE", "CLEMENTINE", "NECTARINE",
        "PAPAYE", "AVOCAT", "CHATAIGNE", "NOISETTE", "AMANDE", "NOIX", "COIN", "MIRABELLE", "RHUBARBE", "PASSION",
        "GRIOTTE", "MANDARINE", "KAKI", "PIGNON", "KIWANO", "CARAMBOLE", "FEIJOA", "DURIAN", "POMELO", "CANNEBERGE"
    ],
    Pays: [
        "FRANCE", "ITALIE", "JAPON", "CANADA", "BRESIL", "ESPAGNE", "MAROC", "CHINE", "MEXIQUE", "EGYPTE",
        "ALGERIE", "BELGIQUE", "SUISSE", "GRECE", "INDE", "PORTUGAL", "RUSSIE", "TURQUIE", "VIETNAM", "CONGO",
        "CHILI", "NORVEGE", "SUEDE", "MONACO", "ISLANDE", "ALLEMAGNE", "ARGENTINE", "AUSTRALIE", "AUTRICHE", "BOLIVIE",
        "COLOMBIE", "DANEMARK", "FINLANDE", "GHANA", "HAITI", "IRLANDE", "JORDANIE", "KENYA", "LIBAN", "MALI",
        "NIGERIA", "PANAMA", "PAYS-BAS", "PEROU", "POLOGNE", "SENEGAL", "THAILANDE", "TUNISIE", "URUGUAY", "ZAMBIE"
    ],
    Sports: [
        "FOOTBALL", "TENNIS", "BASKET", "KARATE", "JUDO", "BOXE", "RUGBY", "NATATION", "ESCRIME", "GOLF",
        "SURF", "SKATE", "HOCKEY", "VOILE", "CANOE", "VELO", "AVIRON", "SQUASH", "DESSIN", "DANSE",
        "COURSE", "MARCHE", "TREKKING", "TRIATHLON", "APNEE", "CYCLISME", "ESCALADE", "GYMNASTIQUE", "HANDBALL", "VOLLEYBALL",
        "BADMINTON", "PING-PONG", "CATCH", "BILLARD", "EQUITATION", "LUGE", "SKI", "SNOWBOARD", "PATINAGE", "YOGA",
        "PILATES", "ARCHERIE", "BASEBALL", "CURLING", "KAYAK", "KITESURF", "PETANQUE", "POLO", "RAQUETTE", "KENDO"
    ],
    Application: [
        "INSTAGRAM", "TIKTOK", "FACEBOOK", "SNAPCHAT", "WHATSAPP", "YOUTUBE", "TWITTER", "NETFLIX", "SPOTIFY", "DISCORD",
        "TELEGRAM", "LINKEDIN", "TINDER", "DEEZER", "AMAZON", "UBER", "AIRBNB", "FIREFOX", "WAZE", "SHAZAM",
        "OUTLOOK", "GMAIL", "PHOTOSHOP", "EXCEL", "CANVA", "LEBONCOIN", "WORD", "HORLOGE", "SKYPE", "PINTEREST",
        "REDDIT", "TWITCH", "EBAY", "VINTED", "Deliveroo", "PLAYSTORE", "CALCULATRICE", "TF1", "TEMU", "PAYPAL",
        "CAPCUT", "LEROYMERLIN", "DOCTOLIB", "FACEBOOK", "MESSENGER", "CHROME", "SAFARI", "WIKIPEDIA", "DUOLINGO", "DISNEY"
    ],
    Cuisine: [
        "POELE", "CASSEROLE", "FOUR", "FRIGO", "MIXEUR", "MARMITE", "TABLIER", "TOQUE", "RECETTE", "EPICE",
        "SEL", "POIVRE", "HUILE", "VINAIGRE", "SUCRE", "FARINE", "LEVURE", "BEURRE", "OEUF", "LAIT",
        "CREME", "PATES", "RIZ", "VIANDE", "POISSON", "LEGUME", "SOUPE", "SAUCE", "GATEAU", "TARTE",
        "POULET", "ROTI", "GRILLADE", "VAPEUR", "MIJOTER", "BOUILLIR", "COUTEAU", "PLANCHE", "PASSOIRE", "FOUET",
        "BALANCE", "MOULE", "ROULEAU", "SPATULE", "LOUCHE", "RAPE", "TAMIS", "PLATEAU", "BOCAL", "TORCHON"
    ]
};